# Generated by Django 5.1.4 on 2025-01-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
